const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { readOwnership, ownershipFor } = require("../scripts/check-architecture");

test("canonical, source, legacy, and generated ownership is explicit", () => {
  const ownership = readOwnership();
  assert.equal(ownership.authorityOrder[0], "canonical");
  assert.equal(ownershipFor("content/courses/DSA5105/course.json", ownership.rules).role, "canonical");
  assert.equal(ownershipFor("data/nus/generated/dsa5105.js", ownership.rules).role, "generated");
  assert.equal(ownershipFor("dist/content/manifest.json", ownership.rules).role, "generated");
});

test("tracked generated bundles identify their generator", () => {
  const file = path.join(__dirname, "..", "data", "nus", "generated", "dsa5105.js");
  assert.match(fs.readFileSync(file, "utf8"), /Generated by scripts\/content-build\.js/);
});
